document.write( '<div class=\"pswp\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n' );
document.write( '	<div class=\"pswp__bg\"></div>\n' );
document.write( '	<div class=\"pswp__scroll-wrap\">\n' );
document.write( '		<div class=\"pswp__container\">\n' );
document.write( '			<div class=\"pswp__item\"></div>\n' );
document.write( '			<div class=\"pswp__item\"></div>\n' );
document.write( '			<div class=\"pswp__item\"></div>\n' );
document.write( '\n' );
document.write( '		</div><div class=\"pswp__ui pswp__ui--hidden\">\n' );
document.write( '			<div class=\"pswp__top-bar\">\n' );
document.write( '				<div class=\"pswp__counter\"></div>\n' );
document.write( '				<button class=\"pswp__button pswp__button--close\" title=\"Close (Esc)\"></button>\n' );
document.write( '				<button class=\"pswp__button pswp__button--share\" title=\"Share\"></button>\n' );
document.write( '				<button class=\"pswp__button pswp__button--fs\" title=\"Toggle fullscreen\"></button>\n' );
document.write( '				<button class=\"pswp__button pswp__button--zoom\" title=\"Zoom in/out\"></button>\n' );
document.write( '				<div class=\"pswp__preloader\"><div class=\"pswp__preloader__icn\">\n' );
document.write( '						<div class=\"pswp__preloader__cut\">\n' );
document.write( '							<div class=\"pswp__preloader__donut\"></div>\n' );
document.write( '						</div>\n' );
document.write( '					</div>\n' );
document.write( '				</div>\n' );
document.write( '			</div>\n' );
document.write( '			<div class=\"pswp__share-modal pswp__share-modal--hidden pswp__single-tap\">\n' );
document.write( '				<div class=\"pswp__share-tooltip\"></div>\n' );
document.write( '			</div>\n' );
document.write( '			<button class=\"pswp__button pswp__button--arrow--left\" title=\"Previous (arrow left)\"> </button>\n' );
document.write( '			<button class=\"pswp__button pswp__button--arrow--right\" title=\"Next (arrow right)\"> </button>\n' );
document.write( '			<div class=\"pswp__caption\">\n' );
document.write( '				<div class=\"pswp__caption__center\"></div>\n' );
document.write( '			</div>\n' );
document.write( '		</div>\n' );
document.write( '	</div>\n' );
document.write( '</div>' );
